version: "2.1"

# docker compose helps us to deploy multiple applications from one repository
services:
  app:
    build: .
    ports:
      - 3001:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017